# Generated by Django 4.1.7 on 2023-03-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Youtube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("is_done", models.BooleanField(default=False)),
                ("path", models.CharField(max_length=200)),
            ],
        ),
    ]
