# Generated by Django 4.1.7 on 2023-03-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0002_remove_youtube_path_youtube_audio_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtube", old_name="audio_file", new_name="file_object",
        ),
    ]
